### ISSUE TITLE
Documentation on creating new plugins 

### ISSUE THREAD

**Issue by ady00** [VarunPatelius/Py-iMessenger#2]
Hello! I've been tinkering with this repository for the past 2 days, and it's worked like a charm so far. However, I couldn't find any documentation on the creation of new plugins in your YouTube playlist. Some clarification in your README or an update to the video playlist would be much appreciated. Thanks!

**Comment by VarunPatelius** [comment]
The end of the General Overview video does contain some information about registering and creating a simple extension. I have an more comprehensive guide that I am yet to edit, but I will close this issue when I post it today.

**Comment by VarunPatelius** [comment]
https://www.youtube.com/watch?v=PDOdPdgD0Yk
