### ISSUE TITLE
Separators

### ISSUE THREAD

**Issue by SnarkyDeveloper** [VarunPatelius/Py-iMessenger#8]
@VarunPatelius I know you don't really care about this repo anymore but I'm curious where it would be possible to update the commands from 
/makeTodo,chores,homework,read but instead having it be /makeTodo chores homework read 

(having them separated by a different character, in this example a space)

**Comment by VarunPatelius** [comment]
https://github.com/VarunPatelius/Py-iMessenger/blob/main/src/backend/manage.py#L97

This is where the command is split along the lines of commas.

**Comment by SnarkyDeveloper** [comment]
Thanks!
